# Use %s in your TrackedValue to slot in the game event text being sent.
# default: **%s**
gameEventFormat = "**%s**"
# Use a first %s in your TrackedValue to slot in a username, and a second to slot in the chat message content.
# default: <@%s> %s
gameChatFormat = "<@%s> %s"
# Use a %s to slot in the skin texture ID / username for your head service of choice!
# default: https://vzge.me/face/256/%s.png
webhookFaceApi = "https://vzge.me/bust/256/%s.png"
# The delay for sending a message from Discord to Minecraft in milliseconds. Set up to make sure that Webhook related Discord Bots such as PluralKit may send messages from users..
# range: 0 - 9223372036854775807
# default: 0
d2mMessageDelay = 2000
# The status message to show on the bridge bot
# default:
statusMessage = "ModFest 26"
# The activity type to show on the bridge bot
# options: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM_STATUS, COMPETING
# default: PLAYING
activityType = "PLAYING"
# Whether to use nicknames defined by players or Minecraft account name on Discord
# default: true
useMinecraftNicknames = true
# A map of text to text replacements from MC -> Discord; useful for Styled Chat Emoji
[m2dReplacements]
	"-" = "‒"
	"" = ":ace_heart:"
	"" = ":agender_heart:"
	"" = ":aroace_heart:"
	"" = ":aro_heart:"
	"" = ":bi_heart:"
	"" = ":blanketcon:"
	"" = ":blob_waaaaa:"
	"" = ":demi_heart:"
	"" = ":femboy_heart:"
	"" = ":furry_pride:"
	"" = ":genderfluid_heart:"
	"" = ":genderflux_heart:"
	"" = ":genderqueer_heart:"
	"" = ":intersex_heart:"
	"" = ":lesbian_heart:"
	"" = ":lil_pineapple:"
	"" = ":modfest:"
	"" = ":nb_heart:"
	"" = ":neurodiversity_heart:"
	"" = ":ohno:"
	"" = ":pan_heart:"
	"" = ":pineapple:"
	"" = ":plural_heart:"
	"" = ":queer_heart:"
	"" = ":queer_prog_heart:"
	"" = ":trans_heart:"
	"" = ":uh:"
	"" = ":vincian_heart:"
	"" = ":winner:"
	"" = ":yeefuckinghaw:"
	"" = ":ananas_great:"
	"" = ":ananas_good:"
	"" = ":ananas_question:"
	"" = ":ananas_none:"
	"" = ":modfest_waaaaa:"
	"" = ":iapprove:"
# A map of text to text replacements from Discord -> MC; useful for Styled Chat Emoji
[d2mReplacements]
	":ace_heart:" = ""
	":agender_heart:" = ""
	":aroace_heart:" = ""
	":aro_heart:" = ""
	":bi_heart:" = ""
	":blanketcon:" = ""
	":blob_waaaaa:" = ""
	":demi_heart:" = ""
	":femboy_heart:" = ""
	":furry_pride:" = ""
	":genderfluid_heart:" = ""
	":genderflux_heart:" = ""
	":genderqueer_heart:" = ""
	":intersex_heart:" = ""
	":lesbian_heart:" = ""
	":lil_pineapple:" = ""
	":modfest:" = ""
	":nb_heart:" = ""
	":neurodiversity_heart:" = ""
	":ohno:" = ""
	":pan_heart:" = ""
	":pineapple:" = ""
	":plural_heart:" = ""
	":queer_heart:" = ""
	":queer_prog_heart:" = ""
	":trans_heart:" = ""
	":uh:" = ""
	":vincian_heart:" = ""
	":winner:" = ""
	":yeefuckinghaw:" = ""
	":ananas_great:" = ""
	":ananas_good:" = ""
	":ananas_question:" = ""
	":ananas_none:" = ""
	":modfest_waaaaa:" = ""
	":iapprove:" = ""
