# Use %s in your TrackedValue to slot in the game event text being sent.
# default: **%s**
gameEventFormat = "**%s**"
# Use a first %s in your TrackedValue to slot in a username, and a second to slot in the chat message content.
# default: <@%s> %s
gameChatFormat = "<@%s> %s"
# Use a %s to slot in the skin texture ID / username for your head service of choice!
# default: https://vzge.me/face/256/%s.png
webhookFaceApi = "https://vzge.me/bust/256/%s.png"
# The delay for sending a message from Discord to Minecraft in milliseconds. Set up to make sure that Webhook related Discord Bots such as PluralKit may send messages from users..
# range: 0 - 9223372036854775807
# default: 0
d2mMessageDelay = 2000
# The status message to show on the bridge bot
# default:
statusMessage = "ModFest 26"
# The activity type to show on the bridge bot
# options: PLAYING, STREAMING, LISTENING, WATCHING, CUSTOM_STATUS, COMPETING
# default: PLAYING
activityType = "PLAYING"
# Whether to use nicknames defined by players or Minecraft account name on Discord
# default: true
useMinecraftNicknames = true
# A map of text to text replacements from MC -> Discord; useful for Styled Chat Emoji
[m2dReplacements]
	"" = "<:blanketcon23:1116460366243840103>"
	"" = "<:blob_waaaaa:971221534742040656>"
	"" = "<:lil_pineapple:959375086228488203>"
	"" = "<:modfest:1003042391596478525>"
	"" = "<:ohno:724245854554161182>"
	"" = "<:pineapple:1008106543079759974>"
	"" = "<:uh:961064383419658270>"
	"" = "<:winner:1008152122916864101>"
	"" = "<:yeefuckinghaw:697606336564822076>"
	"" = "<:ananas_great:1363033139252957398>"
	"" = "<:ananas_good:1363033137097085029>"
	"" = "<:ananas_question:1363033135662497933>"
	"" = "<:ananas_none:1363033133917802577>"
	"" = "<:modfest_waaaaa:1007787960864886915>"
	"" = "<:iapprove:1008151991786164245>"
	"-" = "‒"
# A map of text to text replacements from Discord -> MC; useful for Styled Chat Emoji
[d2mReplacements]
	":blanketcon23:" = "<font 'modfest:emoji'></font>"
	":blob_waaaaa:" = "<font 'modfest:emoji'></font>"
	":lil_pineapple:" = "<font 'modfest:emoji'></font>"
	":modfest:" = "<font 'modfest:emoji'></font>"
	":ohno:" = "<font 'modfest:emoji'></font>"
	":pineapple:" = "<font 'modfest:emoji'></font>"
	":uh:" = "<font 'modfest:emoji'></font>"
	":winner:" = "<font 'modfest:emoji'></font>"
	":yeefuckinghaw:" = "<font 'modfest:emoji'></font>"
	":ananas_great:" = "<font 'modfest:emoji'></font>"
	":ananas_good:" = "<font 'modfest:emoji'></font>"
	":ananas_question:" = "<font 'modfest:emoji'></font>"
	":ananas_none:" = "<font 'modfest:emoji'></font>"
	":modfest_waaaaa:" = "<font 'modfest:emoji'></font>"
	":iapprove:" = "<font 'modfest:emoji'></font>"
